FROM python:3.11.9-alpine3.20

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code/

CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]
